#ifndef EDIT_APPLOC_H
#define EDIT_APPLOC_H

// App string table (generated from src/bin/edit/localization.rs).
// Threading: init once before use; loc() is read-only afterwards.

typedef enum {
    EDIT_LOC_CTRL,
    EDIT_LOC_ALT,
    EDIT_LOC_SHIFT,
    EDIT_LOC_OK,
    EDIT_LOC_YES,
    EDIT_LOC_NO,
    EDIT_LOC_CANCEL,
    EDIT_LOC_ALWAYS,
    EDIT_LOC_FILE,
    EDIT_LOC_FILE_NEW,
    EDIT_LOC_FILE_OPEN,
    EDIT_LOC_FILE_SAVE,
    EDIT_LOC_FILE_SAVE_AS,
    EDIT_LOC_FILE_CLOSE,
    EDIT_LOC_FILE_EXIT,
    EDIT_LOC_EDIT,
    EDIT_LOC_EDIT_UNDO,
    EDIT_LOC_EDIT_REDO,
    EDIT_LOC_EDIT_CUT,
    EDIT_LOC_EDIT_COPY,
    EDIT_LOC_EDIT_PASTE,
    EDIT_LOC_EDIT_FIND,
    EDIT_LOC_EDIT_REPLACE,
    EDIT_LOC_VIEW,
    EDIT_LOC_VIEW_FOCUS_STATUSBAR,
    EDIT_LOC_VIEW_WORD_WRAP,
    EDIT_LOC_HELP,
    EDIT_LOC_HELP_ABOUT,
    EDIT_LOC_UNSAVED_CHANGES_DIALOG_TITLE,
    EDIT_LOC_UNSAVED_CHANGES_DIALOG_DESCRIPTION,
    EDIT_LOC_UNSAVED_CHANGES_DIALOG_YES,
    EDIT_LOC_UNSAVED_CHANGES_DIALOG_NO,
    EDIT_LOC_ABOUT_DIALOG_TITLE,
    EDIT_LOC_ABOUT_DIALOG_VERSION,
    EDIT_LOC_LARGE_CLIPBOARD_WARNING_LINE1,
    EDIT_LOC_LARGE_CLIPBOARD_WARNING_LINE2,
    EDIT_LOC_LARGE_CLIPBOARD_WARNING_LINE3,
    EDIT_LOC_SUPER_LARGE_CLIPBOARD_WARNING,
    EDIT_LOC_WARNING_DIALOG_TITLE,
    EDIT_LOC_ERROR_DIALOG_TITLE,
    EDIT_LOC_ERROR_ICU_MISSING,
    EDIT_LOC_SEARCH_NEEDLE_LABEL,
    EDIT_LOC_SEARCH_REPLACEMENT_LABEL,
    EDIT_LOC_SEARCH_MATCH_CASE,
    EDIT_LOC_SEARCH_WHOLE_WORD,
    EDIT_LOC_SEARCH_USE_REGEX,
    EDIT_LOC_SEARCH_REPLACE_ALL,
    EDIT_LOC_SEARCH_CLOSE,
    EDIT_LOC_ENCODING_REOPEN,
    EDIT_LOC_ENCODING_CONVERT,
    EDIT_LOC_INDENTATION_TABS,
    EDIT_LOC_INDENTATION_SPACES,
    EDIT_LOC_SAVE_AS_DIALOG_PATH_LABEL,
    EDIT_LOC_SAVE_AS_DIALOG_NAME_LABEL,
    EDIT_LOC_FILE_OVERWRITE_WARNING,
    EDIT_LOC_FILE_OVERWRITE_WARNING_DESCRIPTION,
    EDIT_LOC_COUNT = 56
} edit_loc_id_t;

void edit_loc_init(void);
const char *edit_loc(edit_loc_id_t id);

#endif
